apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclone-app
spec:
  selector:
    matchLabels:
      app: cyclone-app
  replicas: 2
  template:
    metadata:
      labels:
        app: cyclone-app
    spec:
      containers:
        - name: cyclone-app
          image: brandonwie/cyclone-image
          ports:
            - containerPort: 3000
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: '1'
          #   requests:
          #     memory: 256Mi
          #     cpu: '0.2'
